- name: update cache
  apt: update_cache=yes

- name: geant4 prerequisites
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - qtbase5-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxmu-dev
    - libmotif-dev
    - libxerces-c-dev
