- name: install prerequisites
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
  - git 
  - cmake 
  - gcc-c++ 
  - gcc 
  - binutils 
  - libX11-devel 
  - libXpm-devel 
  - libXft-devel 
  - libXext-devel

- name: install optional prerequisites
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - gcc-gfortran 
    - openssl-devel 
    - pcre-devel 
    - mesa-libGL-devel 
    - mesa-libGLU-devel 
    - glew-devel 
    - ftgl-devel 
    - mysql-devel 
    - fftw-devel 
    - cfitsio-devel 
    - graphviz-devel 
    - avahi-compat-libdns_sd-devel 
    - libldap-dev 
    - python-devel 
    - libxml2-devel 
    - gsl-static
