- name: update cache
  apt: update_cache=yes

- name: install prerequisites
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - dpkg-dev
    - make
    - cmake
    - g++
    - gcc
    - binutils
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev

- name: install optional prerequisites
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - gfortran
    - libssl-dev
    - libpcre3-dev
    - xlibmesa-glu-dev
    - libglew1.5-dev
    - libftgl-dev
    - default-libmysqlclient-dev
    - libfftw3-dev
    - libcfitsio-dev
    - graphviz-dev
    - libavahi-compat-libdnssd-dev
    - libldap2-dev
    - python-dev
    - libxml2-dev
    - libkrb5-dev
    - libgsl0-dev
    - libqt4-dev
